# Copyright 1999-2008 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.2.2 (rev. 214)
EAPI="4"

PYTHON_DEPEND="2"
SUPPORT_PYTHON_ABIS="1"
RESTRICT_PYTHON_ABIS="3.*"
PYTHON_MODNAME="java2python"

inherit distutils

DESCRIPTION="java2python:  Imperfect Translation of Java Source Code to Python"
HOMEPAGE="http://code.google.com/p/java2python/"
SRC_URI="http://java2python.googlecode.com/files/${P}.tar.gz"
LICENSE="GPL-2"
KEYWORDS="~amd64"
SLOT="0"
IUSE=""
