# Copyright 1999-2009 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.2.2 (rev. 214)

PYTHON_MODNAME="parsedatetime"

inherit distutils


DESCRIPTION="Parse human-readable date/time expressions"
HOMEPAGE="http://code-bear.com/code/parsedatetime/"
SRC_URI="http://code-bear.com/code/parsedatetime/${P}.tar.gz"
LICENSE="Apache-2.0"
KEYWORDS="~amd64"
SLOT="0"
IUSE="doc examples"
DEPEND="dev-python/setuptools"

src_install() {
	distutils_src_install
	if use doc; then
		dodoc "${S}"/docs/*
	fi
	if use examples; then
		insinto /usr/share/doc/"${PF}"/examples
		doins -r "${S}"/examples/*
	fi
}

