# Copyright 1999-2008 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.2.1 (rev. 204)

EAPI=5
PYTHON_COMPAT=( python{2_5,2_6,2_7} )

inherit distutils-r1

MY_PN="PyHesiod"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="PyHesiod - Python bindings for the Heisod naming library"
HOMEPAGE="http://ebroder.net/code/PyHesiod"
SRC_URI="http://pypi.python.org/packages/source/P/PyHesiod/${MY_P}.tar.gz"
LICENSE="MIT"
KEYWORDS="~amd64"
SLOT="0"
IUSE=""
