# Copyright 1999-2009 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.2.2 (rev. 214)

EAPI=5

PYTHON_COMPAT=( python{2_5,2_6,2_7} )

inherit distutils-r1

DESCRIPTION="An autocompletion library for Python"
HOMEPAGE="http://code.google.com/p/pysmell"
SRC_URI="http://pypi.python.org/packages/source/p/pysmell/${P}.zip"
LICENSE="BSD-2"
KEYWORDS="~amd64"
SLOT="0"
IUSE=""
DEPEND="app-arch/unzip"

