# Copyright 1999-2008 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.2.2 (rev. 214)
EAPI="4"

PYTHON_DEPEND="2"
SUPPORT_PYTHON_ABIS="1"
RESTRICT_PYTHON_ABIS="3.*"

PYTHON_MODNAME="pymbolic"

inherit distutils


DESCRIPTION="A package for symbolic computation"
HOMEPAGE="http://mathema.tician.de/software/pymbolic"
SRC_URI="http://pypi.python.org/packages/source/p/pymbolic/${P}.tar.gz"
LICENSE="MIT"
KEYWORDS="~amd64"
SLOT="0"
IUSE=""
DEPEND="dev-python/setuptools"
RDEPEND=">=dev-python/pytools-2"

src_test() {
	PYTHONPATH=. "${python}" setup.py test || die "tests failed"
}

