# Copyright 1999-2009 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.2.2 (rev. 214)
EAPI="4"

PYTHON_DEPEND="2"
SUPPORT_PYTHON_ABIS="1"
RESTRICT_PYTHON_ABIS="3.*"

PYTHON_MODNAME="synoptic"

inherit distutils


DESCRIPTION="An AJAXy notes manager"
HOMEPAGE="http://mathema.tician.de/software/synoptic"
SRC_URI="http://pypi.python.org/packages/source/s/synoptic/${P}.tar.gz"
LICENSE="MIT"
KEYWORDS="~amd64"
SLOT="0"
IUSE="doc"
DEPEND="dev-python/setuptools"
RDEPEND=">=dev-python/paste-1.6
	>=dev-python/sqlalchemy-0.4.4
	>=dev-python/simplejson-1.7
	>=dev-python/parsedatetime-0.8.4"

src_install() {
	distutils_src_install
	if use doc; then
		dodoc "${S}"/doc/*
	fi

}

