# Copyright 1999-2009 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.2.1 (rev. 204)

EAPI="4"
PYTHON_DEPEND="2"
SUPPORT_PYTHON_ABIS="1"
RESTRICT_PYTHON_ABIS="3.*"

inherit distutils subversion

DESCRIPTION="ctypeslib - useful additions to the ctypes FFI library"
HOMEPAGE="UNKNOWN"
ESVN_REPO_URI="http://svn.python.org/projects/ctypes/trunk/ctypeslib/"
LICENSE="MIT"
KEYWORDS=""
SLOT="0"
IUSE=""
