# Copyright 1999-2009 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.2.2 (rev. 214)

PYTHON_MODNAME="stopwatch"

inherit distutils


DESCRIPTION="stopwatch is a very simple python module for measuring time."
HOMEPAGE="http://code.google.com/p/7oars/"
SRC_URI="http://7oars.googlecode.com/files/${P}.tar.gz"
LICENSE="BSD-2"
KEYWORDS="~amd64"
SLOT="0"
IUSE=""
DEPEND="dev-python/setuptools"

